name: Apply the latest sink filter to GCP

on:
  push:
    branches:
      - main

env:
  # Set Sysdig URL
  SYSDIG_URL: https://app.au1.sysdig.com

jobs:
  apply-terraform:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Set GCP project ID
      - name: Set GCP Project ID
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Step 4: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Step 5: Set environment variables
      - name: Set environment variables
        run: |
          echo "Setting environment variables..."
          export TF_VAR_GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
          export TF_VAR_SYSDIG_SECURE_ENDPOINT_URL=$SYSDIG_URL
          export TF_VAR_SYSDIG_SECURE_API_TOKEN=${{ secrets.SYSDIG_SECURE_API_TOKEN }}

      # Step 6: Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # Step 7: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
