name: Apply the latest sink filter to GCP

on:
  push:
    branches:
      - main

env:
  # Set Sysdig URL
  SYSDIG_URL: https://app.au1.sysdig.com

jobs:
  apply-terraform:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Set GCP project ID
      - name: Set GCP Project ID
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Step 4: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Step 5: Set environment variables
      - name: Terraform Init and Apply
        env:
          TF_VAR_GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_GCP_REGION: ${{ secrets.GCP_REGION }}
          TF_VAR_SYSDIG_SECURE_ENDPOINT_URL: ${{ secrets.SYSDIG_SECURE_ENDPOINT_URL }}
          TF_VAR_SYSDIG_SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}
        run: |
          terraform init
          terraform plan -var="GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" -var="GCP_REGION=${{ secrets.GCP_REGION }}" -var="SYSDIG_SECURE_ENDPOINT_URL=${{ secrets.SYSDIG_SECURE_ENDPOINT_URL }}" -var="SYSDIG_SECURE_API_TOKEN=${{ secrets.SYSDIG_SECURE_API_TOKEN }}"
          terraform apply -auto-approve
        working-directory: ./terraform
        